name: Publish Digger
on:
  push:
    branches:
      - main
    paths:
      - '**/digger'
      - '**/publish-digger.yaml'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Curl
        run: sudo apt install curl -y
      - name: Install Docker
        run: sudo curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      - name: Checkout code
        uses: actions/checkout@v3
