name: publish.digger
run-name: Publish Digger
on:
  push:
    branches:
      - main
    paths:
      - '**/digger'
      - '**/publish-digger.yaml'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
